### ISSUE TITLE
Survey 第三方套件ê授權

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/squirrel#13]

**Comment by ngoohebi** [comment]
Chhōe所有ê授權kám ē-sái商業使用。

**Comment by a8568730** [comment]
https://github.com/rime/squirrel#%E8%87%B4%E8%AC%9D

> 本品引用了以下開源軟件：
> - Boost C++ Libraries (Boost Software License)
> - darts-clone (New BSD License)
> - google-glog (New BSD License)
> - Google Test (New BSD License)
> - LevelDB (New BSD License)
> - librime (New BSD License)
> - OpenCC / 開放中文轉換 (Apache License 2.0)
> - plum / 東風破 (GNU Lesser General Public License 3.0)
> - Sparkle (MIT License)
> - UTF8-CPP (Boost Software License)
> - yaml-cpp (MIT License)

**Comment by sih4sing5hong5** [comment]
因為`squirrel`是GPL，所以嘛是攏愛公開

**Comment by ngoohebi** [comment]
Koat-tēng su-ji̍p-hoat pún-thé sī kong-khai--ê. Su-ji̍p-hoat hong-àn to̍h bô.
