### ISSUE TITLE
add_data_files, terra_pinyin.schema.yaml調整

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/squirrel#24]
因為 #23 有走 bash add_data_files，
毋過 .travis.yml 有kā `terra_pinyin.schema.yaml` 提掉
https://github.com/i3thuan5/ThoanTaigi/blob/master/.travis.yml#L15

因為`terra_pinyin.schema.yaml`提掉，`add_data_files`就bô作用，

按呢`terra_pinyin.schema.yaml`若bô提掉，敢有法度sūn-sī make?
若是一定ài提掉，按呢需要備份本底ê `project.pbxproj`
```
cp project.pbxproj project.pbxproj.pihun
bash add_data_files
sed -i '' terrra...
xcod build
mv project.pbxproj project.pbxproj.build
mv project.pbxproj.pihun project.pbxproj
```

**Comment by ngoohebi** [comment]
Kái chò án-ne: https://github.com/i3thuan5/ThoanTaigi/pull/27
