### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/squirrel#5]
Tsit-má ū 3 tsân, `develop_ThoanTaigi`, `master_ThoanTaigi` kah `master`. Lán Git workflow iōng 2 tsân ìng-tong tō ū-kàu.

- `master` tsiânn-tsò tsiânn-tsò khai-huat--ê
- `release` tsiânn-tsò beh tshut-pán--ê

Hó-tshù sī, khah ha̍h ta̍k-ke uì `master` khai-sí khai-huat ê kuàn-sì.

**Comment by ngoohebi** [comment]
Í-keng kái chò Git Flow. Goân-té ê branch í-keng thâi tiāu.
