### ISSUE TITLE
原底khoo-pi yaml ê代誌

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/squirrel#6]
原本是khok-pi `data/plum` 
https://github.com/i3thuan5/ThoanTaigi/blob/master/package/add_data_files#L72
新做法是寫tī
https://github.com/i3thuan5/ThoanTaigi/blob/master/scripts/postinstall

**Comment by ngoohebi** [comment]
Í-keng kā "plum" the̍h tiāu.
