### ISSUE TITLE
Miâ hián-sī tw.ithoan.inputmethod.ThoanTaigi

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/squirrel#8]
我鬥好勢了後，leh選輸入法ê時陣，伊名是顯示 `tw.ithoan.inputmethod.ThoanTaigi`

**Comment by ngoohebi** [comment]
Chiàu kóng èng-kai sī ē khì lia̍h 1-ê só͘-chai ê miâ-chheng, góa koh chhì khòaⁿ-māi, būn-tê tī tó-ūi.

**Comment by ngoohebi** [comment]
Í-keng kā chok-gia̍p hē-thóng sī "Eng-gí", "Tâi-oân Hôa-gí" lóng siat-tēng hó-sè.
