### ISSUE TITLE
咱改ê部份

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/squirrel#9]
因為 #5 物件傷濟無好看。

咱主要是改

1. 專案名kah顯示ê資料
2. 改路徑，kah本底 squirrel 無仝
2. yaml用咱ê
3. 自動更新
4. 鬥了登出

敢koh有sánn功能我落勾無寫著？
逐項開luā濟時間？

**Comment by ngoohebi** [comment]
Che kám beh ti̍t-chiap siá tī chia? (Kong-khai--ê)

**Comment by ngoohebi** [comment]
Chū-tōng keng-sin nā sī khǹg tī Mac ê App store to̍h bián koh iōng chū-tōng keng-sin ê ki-chè.

**Comment by sih4sing5hong5** [comment]
> Che kám beh ti̍t-chiap siá tī chia? (Kong-khai--ê)

無差--lah，huann-ti̍t 若人有興趣，in 會自公版ê去改--lah

**Comment by a8568730** [comment]
> Chū-tōng keng-sin nā sī khǹg tī Mac ê App store to̍h **bián koh** iōng chū-tōng keng-sin ê ki-chè.

 Ì-sù sī... Nā khǹg tī Mac APP, in ū siá-hó tsū-tōng king-sin; lán **bián koh līng-guā** ka-tī tshuē thò-kiānn?

**Comment by a8568730** [comment]
> 因為 #5 物件傷濟無好看。

今仔日 ē-poo 多謝 Hê-bí 當面解說。
`ithuan/develop_ThoanTaigi` kah `rime/master` 有 tsiah-nī 濟檔案無 kâng，是因為振動著：
* rime 內底 ê [Sparkle](https://sparkle-project.org/) 設定
* xcodeproject 專案名改號做 ThoanTaigi

Hia-ê 檔案 lóng 是自動改--ê，Hê-bí bô 振動。

**Comment by ngoohebi** [comment]
1. PR https://github.com/i3thuan5/ThoanTaigi/pull/14
2. PR https://github.com/i3thuan5/ThoanTaigi/pull/15

**Comment by sih4sing5hong5** [comment]
`鬥了登出`是本底就有，抑是咱另外加--ê？若是咱加--ê，程式tī toh?
因為tsa̋ng試有這ê功能

**Comment by sih4sing5hong5** [comment]
> `鬥了登出`是本底就有，抑是咱另外加--ê？若是咱加--ê，程式tī toh?
> 因為tsa̋ng試有這ê功能

punte就會登出
